version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "09:00"
      timezone: "Asia/Tokyo"
    reviewers:
      - "homoluctus"
    commit-message:
      prefix: "fix"
      include: "scope"
    allow:
      - dependency-type: "production"
