name: Release

on:
  push:
    tags:
      - '[0-9]*.[0-9]*.[0-9]*'

jobs:
  pypi:
    name: Release to PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install --no-dev

      - name: Release
        env:
          POETRY_USERNAME: ${{ secrets.POETRY_USERNAME }}
          POETRY_PASSWORD: ${{ secrets.POETRY_PASSWORD }}
        run: make release username=$POETRY_USERNAME password=$POETRY_PASSWORD

  github:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Release
        run: npx github-release-notes release --token=${{ secrets.GITHUB_TOKEN }} -d -D prs
